services:
  app:
  image: dns-helper
  build:
    context: .
    dockerfile: frontend/Dockerfile
    container_name: dns-helper
    restart: always

  db:
    image: mariadb
    container_name: dns-helper-db
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - default
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password # Change this
      MYSQL_DATABASE: dns-helper # Change this optional
      MYSQL_USER: user # Change this
      MYSQL_PASSWORD: password # Change this
  
  server:
    depends_on:
      - db
    image: dns-helper-api
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: dns-helper-api
    environment:
      DATABASE_URL: db
      DB_PORT: 3306
      DB_NAME: dns-helper
      DB_USER: user
      DB_PASSWORD: password
      PORT: 3000
      NODE_ENV: production
      FRONTEND_URL: app
    restart: always
    networks:
      - default
  
  nginx:
    image: nginx:alpine
    container_name: dns-helper-nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - server

volumes:
  db-data:
    name: dns-helper-db-data
networks:
  proxy:
    external: true