POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Mike Vautour",
  "email": "mike@mike.com",
  "password": "password"
}

### Delete record
DELETE http://localhost:3000/api/users/3
