### Create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@test.com",
  "password": "4kjg08s789o8dpfobjh"
}

### Get users
GET http://localhost:3000/api/users

### Edit user
PUT http://localhost:3000/api/users/b9367782-12f5-43fb-a9a4-a7681bc8428c
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@test.com",
  "password": "4kjg08s789o8dpfobjh"
}

### Delete record
DELETE http://localhost:3000/api/users/3
